package com.ntg.core.commom.util

val Categories = listOf(
  "Income",
  "Salary",
  "Self-employed income",
  "Bonus",
  "Tips",
  "Tax refund",
  "Gifts received",
  "Alimony received",
  "Child support received",
  "Rental income",
  "Dividend income",
  "Interest earned",
  "Housing",
  "Mortgage/rent",
  "Homeowners association (HOA fees)",
  "Homeowners insurance",
  "Property insurance (i.e., jewelry)",
  "Home repairs/Maintenance",
  "Property taxes",
  "Home improvement",
  "Furnishings",
  "Home Services",
  "House cleaning",
  "Lawn care",
  "Security system",
  "Pest control",
  "Utilities",
  "Natural gas Electricity",
  "Landline/Home phone",
  "Mobile phone",
  "Home Internet",
  "Garbage",
  "Recycling",
  "Water",
  "Sewer",
  "Household Items",
  "Cleaning supplies",
  "Paper products",
  "Tools",
  "Toiletries",
  "Laundry supplies",
  "Postage",
  "Furniture",
  "Home décor",
  "Pool supplies",
  "Food",
  "Groceries",
  "Fast food",
  "Coffee shops",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Drinks",
  "Snacks",
  "Transportation",
  "Car payment/lease payments",
  "Car insurance",
  "Gas",
  "Oil change",
  "Maintenance Repairs",
  "Personal property taxes",
  "Registration",
  "Public transportation",
  "Ride sharing (Uber, Lyft)",
  "Tolls",
  "Parking",
  "Roadside assistance (AAA)",
  "Medical Health",
  "Health insurance",
  "Dental insurance",
  "Vision insurance",
  "Prescription Medications",
  "Doctor bills",
  "Dentist visits",
  "Hospital bills",
  "Optometrist",
  "Glasses/contacts",
  "Chiropractor visits",
  "Vitamins/supplements",
  "Insurance",
  "Life insurance",
  "Disability insurance",
  "Long-term care insurance",
  "Umbrella policy",
  "Identity theft",
  "Kids",
  "Tuition",
  "Daycare",
  "Babysitter/Nanny",
  "Baby necessities, formula",
  "Summer camp",
  "School or extra-curricular activities",
  "School supplies",
  "School lunches",
  "Lessons",
  "Allowance",
  "Toys",
  "Kids’ discretionary spending",
  "Child support",
  "Clothing",
  "Pets",
  "Veterinarian visits",
  "Pet food",
  "Pet medication (i.e., flea prevention, shots, heartworm medication)",
  "Pet toys/beds",
  "Pet accessories (i.e.,leash, collar, etc.)",
  "Pet grooming",
  "Pet insurance",
  "Subscriptions/Streaming Services",
  "Netflix, Hulu",
  "Amazon Prime",
  "Music (Spotify, Pandora)",
  "Sports TV subscription (i.e., ESPN, Fox Sports)",
  "Software subscriptions",
  "Magazines",
  "Professional society annual fees",
  "Clothing",
  "Work clothing",
  "Athletic clothing",
  "Leisure clothing",
  "Alterations",
  "Dry cleaning",
  "Personal Care",
  "Haircuts",
  "Hair coloring",
  "Hair products",
  "Cosmetics",
  "Nail salon",
  "Eyebrows",
  "Massages",
  "Spa services",
  "Grooming",
  "Gym membership",
  "Counseling Therapy",
  "Personal Development",
  "Books",
  "Personal coach",
  "Self-improvement",
  "Conferences",
  "Online courses",
  "In-person courses",
  "Financial/Professional Fees",
  "Financial advisor",
  "Lawyer/Attorney fees",
  "Tax professional (CPA, online accounting firm)",
  "Business consultant",
  "Recreation/Fun",
  "Movies",
  "Concerts",
  "Hobbies/Crafts",
  "Hosting parties",
  "Books",
  "Entertainment",
  "Sporting events",
  "Travel",
  "Vacation",
  "Trips to see family",
  "Trips for weddings, bachelor/bachelorette parties",
  "Souvenirs",
  "Baggage fees",
  "TSA precheck or global entry",
  "Technology",
  "Mobile phone",
  "Computer/Computer accessories",
  "Speaker system",
  "WI-FI mesh system / WI-FI extender",
  "Smart home (i.e., Amazon Echo, Fire, Nest, Google)",
  "Gaming system/Video games/Gaming accessories",
  "Gifts",
  "Family birthday gifts",
  "Friend birthday gifts",
  "Wedding shower gifts",
  "Anniversary gifts",
  "Baby shower gifts",
  "Teacher gifts",
  "Service-person gifts (mail carrier, home service, personal assistant)",
  "Thank you gifts",
  "Holiday gifts",
  "Special occasions",
  "Charitable Giving",
  "Charity Donations",
  "Tithing",
  "Religious",
  "Community",
  "Political",
  "Non-cash donations (i.e., Goodwill, Salvation Army, clothing, canned food, electronics, stock, etc)",
  "Savings Goals/Investing",
  "College savings",
  "Retirement savings",
  "New car savings",
  "Health savings account",
  "Emergency fund",
  "Brokerage investments",
  "Traditional/Roth IRA",
  "Down payment savings",
  "Debt Payments",
  "Credit card debt",
  "Student loan debt",
  "Medical debt",
  "Personal loans",
  "Auto loan payments",
  "Back taxes",
  "Past due bills",
  "Alimony",
)
